# Generated by Django 4.1.4 on 2022-12-17 17:30

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("dogs", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Photo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("photo", models.URLField()),
                (
                    "description",
                    models.CharField(
                        blank=True,
                        max_length=300,
                        null=True,
                        validators=[django.core.validators.MinLengthValidator(10)],
                    ),
                ),
                ("publication_date", models.DateField(auto_now=True)),
                (
                    "dog",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT, to="dogs.dog"
                    ),
                ),
            ],
        ),
    ]
